packages/pglite/src/index.ts
I noticed that it fails to run in Node.js because it relied on `CustomEvent` as a global which isn't exposed in Node.js unless you pass `--experimental-global-customevent`.
This PR adds a polyfill for `CustomEvent` when in Node.js. I tested this and it now works both on local Node.js as well as in WebContainer (which you could test once a new version is released). If you wanna try it yourself, you can fork [this project](https://stackblitz.com/edit/node-oqtitn?file=index.js) and update the version once there's a new one that includes the fix.
=> Polyfill CustomEvent in Node.js

README.md
Git submodule need to be initialized and updated before running build, as local `postgres` source code is required.
=> docs: Add git submodule initialization as build prerequirement

packages/pglite/Makefile, packages/pglite/scripts/modify-postgres-js.js, packages/pglite/src/pglite.ts
This gives us a 2-3x speed boost and reduces the side of the bundle by about a 1/3.
See https://github.com/electric-sql/postgres-wasm/pull/6
=> chore: Remove asyncify

packages/pglite/Makefile, packages/pglite/README.md, packages/pglite/examples/plpgsql.html, packages/pglite/package.json, packages/pglite/src/pglite.ts, packages/pglite/tsup.config.ts
Replaces #42 
See also https://github.com/electric-sql/postgres-wasm/pull/7
Closes #36 
Dev build: [electric-sql-pglite-0.0.2.tgz](https://github.com/electric-sql/pglite/files/14731639/electric-sql-pglite-0.0.2.tgz)
Install with:
```
npm install ./path/to/electric-sql-pglite-0.0.2.tgz
```
=> feature: PL/PGSQL Support via static linking

packages/pglite/src/initdb.ts, packages/pglite/src/pglite.ts, packages/pglite/src/utils.ts, packages/pglite/tsup.config.ts
Fixes https://github.com/electric-sql/pglite/issues/34
The `import.meta.url` call resolves to a path that starts with a forward slash, that Windows cannot handle. (see https://github.com/nodejs/node/issues/37845)
Using the Node URL API to resolve a file URL to a path works, but I understand that the PGLite code works across multiple environments so either we need to polyfill this API or write our own implementation of something that works around this issue (like a very ugly regex?)
=> fix(pglite): Fix Windows path resolution

packages/pglite/src/worker/index.ts
I found bug when using storage in web worker, it always fallback to `nodefs` no matter what storage we use. turns out, when we initialize `PGLiteWorker`, we parse `dataDir`
```ts
const { dataDir: dir, fsType } = parseDataDir(dataDir);
this.dataDir = dir;
```
now `dataDir` is the parsed value, for example from `idb://my-database` to only `/my-database` without `idb://`. then when we initialize the worker, we are using parsed value instead the the raw value, and this value will be parsed again in `PGLite`
```ts
async #init() {
await this.#worker.init(this.dataDir, { debug: this.debug });
this.#ready = true;
}
```
so no mattter what storage used in web worker, it's always using `nodefs`, because we always parsing the parsed value to `PGLite`
=> Fix invalid storage in webworker

.gitignore, packages/pglite/src/initdb.ts, packages/pglite/src/interface.ts, packages/pglite/src/parse.ts, packages/pglite/src/pglite.ts, packages/pglite/src/types.ts, packages/pglite/src/utils.ts, packages/pglite/src/worker/index.ts, packages/pglite/tests/basic.test.js, packages/pglite/tests/types.test.js
Resolves [this issue](https://github.com/electric-sql/pglite/issues/68)
Though there was code in `parseResults` to return the `affectedRows` count for INSERT/UPDATE/DELETE queries, it was never being called because of an extra check for a truthy `currentResultSet`, which was initialized to `null` and only populated if there was a message that was a `RowDescriptionMessage` in the list of messages, which may not be present.
Beyond that though, the `currentResultSet` was only pushed into the returning `resultSet` if the message was `RowDescriptionMessage`. I moved this push to `CommandCompleteMessage` instead, which seems to always be either the only or last message returned from a query:
> The response to a SELECT query (or other queries that return row sets, such as EXPLAIN or SHOW) …
=> Resolve bug preventing `affectedRows` count for mutation queries

packages/pglite/src/worker/index.ts
`PGliteWorker` doesn't currently work with webpack 5 (and Next.js) because webpack requires the worker to be loaded in a [specific way](https://webpack.js.org/guides/web-workers/). Instead of:
```ts
const WORKER_URL = new URL("./process.js", import.meta.url);
new Worker(WORKER_URL, { type: "module" });
```
webpack needs you to combine them into one line:
```ts
new Worker(new URL("./process.js", import.meta.url), { type: "module" });
```
I suspect this is because `WORKER_URL` could be dynamically created at runtime which breaks webpack's static analysis. And webpack needs to statically identify this at build time in order to perform special bundling on the worker script.
Created a quick fork `@gregnr/pglite` to test this and all appears to work now in Next 14:
```ts
import { PGliteWorker } …
```
=> Fix web worker syntax for webpack static analysis

packages/pglite/README.md, packages/pglite/examples/notify-worker.html, packages/pglite/examples/notify.html, packages/pglite/src/interface.ts, packages/pglite/src/pglite.ts, packages/pglite/src/worker/index.ts, packages/pglite/src/worker/process.ts, packages/pglite/tests/notify.test.js
This adds support for subscribing to notification using `pg_notify`, the built in postgres async notification system.
To subscribe to a notification:
```js
const unsub = await pg.listen('test', (payload: string) => {
// do something with the payload
});
```
The first arg is the channel to subscribe to, the second the callback that receives the payload.
Calling `.listen` creates the JS side event callback *and* calls `LISTEN channel_name` on the database connection to subscribe to the channel.
To unsubscribe call the function returned by the subscribe call, with unregisters the callback and calls `UNSUBSCRIBE channel_name` on the database connection.
If you want to listen to all notifications the connection receives you can subscribe with the `onNotification(callback)` api, or unsubscribe …
=> Support for pg_notify

packages/pglite/src/interface.ts, packages/pglite/src/pglite.ts
Stacked on #102
The extensions API provides the place to initiate Postgres extensions or plugins:
```js
import { PGlite } from '@electric-sql/pglite'
import { vector } from '@electric-sql/pglite-pgvector'
import { postgis } from '@electric-sql/pglite-postgis'
const db = new PGlite({
path: 'idb://my-db',
extensions: {
vector,
postgis,
}
})
```
plugins would have the interface:
https://github.com/electric-sql/pglite/blob/c0f5766ca0c8b88388fcbe672918b08a81d206ca/packages/pglite/src/interface.ts#L23-L42
`setup` will be called after the runtime is ready, but before starting PG, and would be passed the Emscripten module `mod` and the PGlite instance `pg`:
- Via pg they can call any PGlite apis
- Via emscriptenOpts they can include additional files in the VFS
`init` will be called after starting …
=> Extension API

packages/pglite/examples/dumpDataDir.html, packages/pglite/examples/dumpDataDir.js, packages/pglite/src/definitions/tinytar.d.ts, packages/pglite/src/fs/idbfs.ts, packages/pglite/src/fs/memoryfs.ts, packages/pglite/src/fs/nodefs.ts, packages/pglite/src/fs/tarUtils.ts, packages/pglite/src/fs/types.ts, packages/pglite/src/interface.ts, packages/pglite/src/pglite.ts, packages/pglite/src/worker/index.ts, packages/pglite/src/worker/process.ts, packages/pglite/tests/dump.test.js
This introduces a new `db.dumpDataDir()` method that dumps the databases datadir to a tarball `File` object and where possible gzips it.
To load a dump `File` pass it to the options when starting PGlite:
```
const pg = new PGlite({
loadDataDir: file,
});
```
The file object to load must be either a tar, or tar.gz. For the gzipped version it must have either a file name ending `.tar.gz` or `.tgz`, or have one of the following mime types:
- application/x-gtar
- application/x-tar+gzip
- application/x-gzip
- application/gzip
If you try to load a dump into a filesystem that already has a database initiated, it will throw an error.
To do:
=> Dump and load tarball of a database

packages/pglite/README.md, packages/pglite/examples/live-changes.html, packages/pglite/examples/live-incremental.html, packages/pglite/examples/live.html, packages/pglite/package.json, packages/pglite/src/live/index.ts, packages/pglite/src/live/interface.ts, packages/pglite/tests/live.test.js, packages/pglite/tsup.config.ts
This added a new "Live Query" plugin (our first one).
To use the extension it needs adding to the PGlite instance when creating it:
```js
import { PGlite } from "@electric-sql/pglite";
import { live } from "@electric-sql/pglite/live";
const pg = new PGlite({
extensions: {
live,
},
});
```
There are three methods on the `live` namespace:
- `live.query()` for basic live queries. Less machinery in PG so quicker for small results sets and narrow rows.
- `live.incrementalQuery()` for incremental queries. It materialises the full result set on each update in js. Perfect for feeding into React
- `live.changes()` a lower level api that emits the changes (insert/update/delete) that can then be mapped to mutation in a UI or other datastore.
This is very similar to a standard query, but takes an …
=> Live Query API

packages/pglite/src/interface.ts, packages/pglite/src/pglite.ts, packages/pglite/src/worker/index.ts, packages/pglite/src/worker/process.ts
When passing raw message data directly to PGlite via `execProtocol()` (through [`pg-gateway`](https://github.com/supabase-community/pg-gateway)), pg protocol error messages end up getting thrown by PGlite which means:
- I have to re-create the protocol error message from the `DatabaseError` object
- We lose any other messages that PG sent back (often a `ReadyForQuery` message)
Ideally there would be a way to `execProtocol` without the wrapping logic for this kind of use case. This PR proposes an `execProtocolRaw()` method that simply forwards raw message data in and returns the raw message result from PG.
Alternatively, if there is a way for `execProtocol` to not throw the `DatabaseError` and/or return the full raw message in the event of an error, that should work too.
=> New method `execProtocolRaw()`

packages/pglite/src/pglite.ts, packages/pglite/src/worker/index.ts, packages/pglite/tests/basic.test.js, packages/pglite/tests/targets/base.js
There was previously a bug in Emscripten that resulted in it throwing an error when we closed the database. The code was written to expect this. With a newer Emscripten this no longer happens. I have left the old catch in place so that if we revert Emscripten or it is re-introduced this will continue to work. I have added explicit closes to the tests.
I have also (as its in the same area) added support for the new ECMAScript "Explicit Resource Management": 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management
https://github.com/tc39/proposal-explicit-resource-management
=> Fix close and add support for new stage 3 ECMAScript explicit resource management

packages/pglite/package.json
Adds a "browser" field to package.json to hint to bundlers what is not required in the browser. This is a list of imports that bundlers should ignore when bundling for the web, all Node builtins either used by PGlite directly, or on some code path in the Emscripten generated js.
Fixes #139
=> Add a "browser" field to package.json to hint to bundlers what is not required in the browser

packages/pglite-react/test/react.test.tsx, packages/pglite/src/index.ts, packages/pglite/src/interface.ts, packages/pglite/src/live/index.ts, packages/pglite/src/pglite.ts, packages/pglite/src/types.ts, packages/pglite/src/utils.ts, packages/pglite/tests/format.test.js, packages/pglite/tests/live.test.js, packages/pglite/tests/types.test.js
Live queries use views to save the query in the db and then introspect what tables are used by it. Unfortunately you can't use parameters when creating a view, therefor we have to interpolate the parameters into the sql query.
We do this by introducing a `formatQuery` utility function that interpolates parameters into the query using the Postgres `format` function. Although it requires an instance of PGlite or a transaction as its first argument I decanted to keep it separate rather than a method on pglite/tx as its an advanced utility and not something that should be used all the time.
=> Fix live query params

packages/pglite/src/fs/opfs-ahp/opfsAhp.ts
Fixes subtle bug introduced in #152 where the method is called without being bound to `this`.
=> Fix OPFS AHP state WAL loading

.changeset/config.json, docs/package.json, packages/pglite/package.json, packages/repl/package.json
Turn docs into private package so changeset ignores it
Also bump all packages to `0.2.0` for the release
@samwillis we will have to manually release `pglite-react` and `pglite-sync` before changesets can start bumping those
=> chore: Update package version and release settings

packages/pglite-vue/.gitignore, packages/pglite-vue/README.md, packages/pglite-vue/eslint.config.js, packages/pglite-vue/package.json, packages/pglite-vue/src/dependency-injection.ts, packages/pglite-vue/src/hooks.ts, packages/pglite-vue/src/index.ts, packages/pglite-vue/test-setup.ts, packages/pglite-vue/test/hooks.test.ts, packages/pglite-vue/test/injection.test-d.ts, packages/pglite-vue/test/injection.test.ts, packages/pglite-vue/tsconfig.json, packages/pglite-vue/tsup.config.ts, packages/pglite-vue/vitest.config.ts, pnpm-lock.yaml
Adds Vue.js hooks for PGlite - will need to update documentation as well, and currently the location of `/framework-hooks` has anchors that don't quite work - will fix those up as well.
=> feat: Implement Vue hooks

.github/workflows/build_and_test.yml, .github/workflows/build_wasm_postgres.yml
PRs from forks only get a read-only token from GH and thus cannot write to the pull request comments and the step will fail (see [action docs](https://github.com/peter-evans/create-or-update-comment?tab=readme-ov-file#action-inputs) )
Either we allow these tasks to fail or not run without appropriate permissions for PRs frok public forks or we use [pull_request_target](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target) that does grant read/write permissions on PRs from forks but is a security concern (as anything can be run from an external PR with read/write perms)
I've also updated the cache key to match @pmp-p 's suggestion
=> fix: Don't add artifacts as PR comment on PRs from forks

docs/.vitepress/config.mts
This enables the vitepress local search feature:
=> docs: enable local search

.changeset/sharp-bees-smash.md, packages/pglite-sync/package.json
Inside of the pglite-sync `package.json` I've replaced the non-existing `build` directory with the correct `dist` directory.
=> pglite-sync import can't find source files

.changeset/angry-items-fry.md, packages/pglite-sync/src/index.ts
There seems to be a small typo in the pglite-sync extension. 
Docs are correct though: https://pglite.dev/docs/sync#syncshapetotable-api
=> fix(pglite-sync): unsubscribe function typo

.changeset/purple-bugs-approve.md, .gitignore, cibuild/build-with-docker.sh, packages/pglite/package.json, packages/pglite/tests/triggers.test.js, patches/postgresql-emscripten/src-backend-commands-event_trigger.c.diff, patches/postgresql-wasm/src-backend-commands-event_trigger.c.diff
Addresses https://github.com/electric-sql/pglite/issues/258
In regular postgres, event triggers are disabled in single user mode as per [the docs](https://www.postgresql.org/docs/current/sql-createeventtrigger.html#notes):
> Event triggers are disabled in single-user mode (see [postgres](https://www.postgresql.org/docs/current/app-postgres.html)). If an erroneous event trigger disables the database so much that you can't even drop the trigger, restart in single-user mode and you'll be able to do that.
I've patched `event_triggers.c` to skip the check in order to enable them in single user mode and thus PGlite. I'm not sure what "layer" the patch belongs to @pmp-p would love your input.
I've also added a test suite for the event triggers, and did a little bit of cleanup on the build …
=> feat: Enable event triggers in single user mode

.changeset/happy-waves-obey.md, .changeset/silent-bulldogs-confess.md, .changeset/stupid-seahorses-chew.md, docs/docs/framework-hooks/react.md, docs/docs/framework-hooks/vue.md, packages/pglite-react/src/hooks.ts, packages/pglite-react/test/hooks.test.tsx, packages/pglite-vue/src/hooks.ts, packages/pglite-vue/test/hooks.test.ts, packages/pglite/src/worker/index.ts
Self explanatory, adds `    useLiveSql`` ` hooks to both React and Vue bindings along with docs and tests
=> feat: Add SQL string templating to React and Vue bindings

.changeset/odd-files-itch.md, packages/pglite/src/pglite.ts, packages/pglite/tests/instantiation.test.ts, packages/pglite/vitest.config.ts
Addresses https://github.com/electric-sql/pglite/issues/268
Docs already mention the `.create` factory method having this signature but it does not support it, so I implemented it to match the constructor.
I've added some _very_ basic tests for instantiation, they don't cover all options or even test they work (no checking of the assigned data dir being created) but they're a boilerplate for the method signature existing and we can add to it. Also mind the test is now a typescript test, as vitest and bun both support those - we can migrate the existing ones to .ts as well.
=> fix: Add `dataDir` string arg to `create` factory method

cibuild.sh, patches/interactive_one.c
there are cases where outside auth, where ReadyForQuery should not be sent.
that state is stored in the global "send_ready_for_query" and should have been tested and reset to false each time.
=> should close #223

README.md, docs/docs/index.md
Since Deno 1.46 we also have the possibility to use PGlite in Deno as well. See the [release blog post](https://deno.com/blog/v1.46#nodejs-and-npm-compatibility) and PR [#25030](https://github.com/denoland/deno/pull/25030) and [25049](https://github.com/denoland/deno/pull/25049) in the Deno runtime repository.
Therefore I suggest adding this to the supported runtimes.
What do you think?
=> docs: add deno install command

docs/docs/sync.md
Fixes a typo from `GitHib -> GitHub`.
=> fix: typo in sync.md

.changeset/chilly-shrimps-shake.md, packages/pglite-sync/src/index.ts, packages/pglite-sync/test/sync.test.ts
Should apply all messages from `ShapeStream` transactionally (even though with chunking you cannot guarantee that the batch of messages received form a transaction) - previously was using one transaction per message and blocking the main loop as well!
We could potentially remove the transaction altogether but I'm assuming that pg might optimize writing many messages together when committing as a transaction either way.
I've also awaited each transaction to finish as the new version of `ShapeStream` will be able to apply backpressure based on the callback provided to process messages, and avoid flooding PG
=> fix: Transactional application of `ShapeStream` messages

.changeset/giant-mice-dream.md, docs/docs/api.md, packages/pglite/examples/dump-data-dir.html, packages/pglite/src/interface.ts, packages/pglite/src/pglite.ts, packages/pglite/src/utils.ts
This adds additional options for the wasmModule and fsBundle, along with caching of the default ones if used.
This should enable a route to running in a Cloudflare worker (pending further changes) as you can do something like:
```ts
import { PGlite } from '@electric-sql/pglite';
import wasm from '@electric-sql/pglite/dist/postgres.wasm';
import fsBundle from '@electric-sql/pglite/dist/postgres.wasm';
pg = await PGlite.create({
wasmModule: wasm,
fsBundle: fsBinary,
});
```
We had something working similar to this in the old v0.1.n version of PGlite on Cloudflare
Fixes: #329 #81
=> feature: wasmModule and fsBundle options and caching of module+fsBundle

.changeset/tender-otters-lie.md, packages/pglite/src/base.ts, packages/pglite/src/interface.ts, packages/pglite/src/live/index.ts, packages/pglite/src/parse.ts, packages/pglite/src/pglite.ts, packages/pglite/src/types.ts, packages/pglite/src/utils.ts, packages/pglite/src/worker/index.ts, packages/pglite/tests/basic.test.js, packages/pglite/tests/format.test.js, packages/pglite/tests/types.test.ts, packages/pglite/tests/xml.test.ts
This is based on #306 but additionally refactors much of the type handling. It also lays the foundation for users to add they own serialises and parser to a PGlite instance either directly or via a plugin/extension - this will come in a later PR.
In the old version type serialization was driven by inferring the type on the JS side, converting to a serialised string, and then setting the type OID on the query for each parameter.
This new version uses the "describe" protocol message to get the expected type of each parameter in a query, and then try and serialise the value based on that. This is based on how it's done in [postgres.js](https://github.com/porsager/postgres/blob/master/src/types.js)
=> chore: refactor serialization to be driven by expected types from Postgres

.changeset/chilly-shrimps-shake.md, .changeset/orange-bears-sing.md, docs/docs/sync.md, packages/pglite-sync/package.json, packages/pglite-sync/src/index.ts, packages/pglite-sync/test/sync.test.ts, pnpm-lock.yaml
Creates a meta table for storing shape subscription information - uses a provided `shapeKey` to determine whether it should persist things and how to index the persisted shapes.
I started by automatically persisting based on things like the shape definition and the table it syncs into, but like @samwillis  probably had already figured out there's complexities in mapping the shape etc that makes it hard to automatically infer how to persist it.
I propose keeping the option undocumented until we get reference counting as well, but for now adding a `shapeKey` would persist the shape and reset the table naively when needing to refetch.
=> feat: PGlite-sync naive resumability

.changeset/breezy-crabs-warn.md, packages/pglite/src/templating.ts, packages/pglite/tests/templating.test.js
It would previously throw on `value._templateType` as you can't access props on `null`
=> fix: sql tagged template method to correctly handle null values

.changeset/twelve-foxes-care.md, packages/pglite-sync/test/sync.test.ts, packages/pglite/tsconfig.json
Fixes https://github.com/electric-sql/pglite/issues/320
=> fix: Use correct path alias for `@electric-sql/pg-protocol` to bundle it with PGlite

.changeset/purple-sheep-whisper.md, packages/pglite-sync/src/index.ts, packages/pglite-sync/test/sync.test.ts
Refetch message would not clear in memory aggregated changes, and thus would still commit them afterwards
=> fix: Fix refetch clearing aggregation

.changeset/funny-candles-warn.md, packages/pglite/package.json
Should fix #355
Regression was introduced here https://github.com/electric-sql/pglite/commit/2831c3401ae146702106c64a8bb25f2bbcfd8b14 with the use of `const fs = await import('fs/promises')`
=> fix: add `fs/promises: false` to the browser config in package.json to exclude it from browser builds

.changeset/cyan-dolls-double.md, packages/pglite/package.json
Currently esbuild errors when targeting browser:
```
✘ [ERROR] Could not resolve "util"
node_modules/.pnpm/@electric-sql+pglite@0.2.11/node_modules/@electric-sql/pglite/dist/chunk-SJVDOE3S.js:1:11418:
1 │ ...r(r){let{promisify:e}=await import("util"),{gzip:t}=await import("zlib");ret...
╵                                       ~~~~~~
The package "util" wasn't found on the file system but is built into node. Are you trying
to bundle for node? You can use "platform: 'node'" to do that, which will remove this
error.
```
This PR adds `util` to package.json browser configuration alongside existing node modules.
=> Add `util` to package.json browser config to exclude it in browser builds

.changeset/sharp-wolves-protect.md, packages/pglite/examples/basic.html, packages/pglite/src/types.ts, packages/pglite/tests/types.test.ts
We changed how we chose the method to encode parameters from being inferred from the JS type, to using the Postgres "Describe" wire protocol message to ask what types Postgres is expecting for each parameter. This is how postgres.js does it, rather than node-postgres.
What this meant was that if you manually ran JSON.stringify on a JS object and passed it as a parameter to PGlite it was inserted into the JSON(B) column as a JSON string (think stringifying twice)  not a JSON object. If you then tried to extract vales from it, they would be null.
This is obv not the expected behavour, a user would want to be able to pass a string thats already JSON encoded to as a param.
=> fix: string passed as param expecting JSON should be treated as string encoded JSON

.changeset/big-wasps-thank.md, packages/pglite-sync/src/index.ts, packages/pglite-sync/test/sync.test.ts
Electric can emit updates with no columns to change, this resulted in invalid SQL in a query that would be redundant. This change skips those messages.
=> fix(pglite-sync): Filter out update messages that don't modify any columns

.changeset/chilled-tomatoes-whisper.md, .changeset/smooth-badgers-move.md, packages/pglite/src/live/index.ts, packages/pglite/src/live/interface.ts, packages/pglite/tests/live.test.ts
This fixes live queries when they are querying a view rather than a table. It now recursively introspects the dependencies of the query to find all tables it depends on.
It also extends the live query return values to allow subscribing with a callback after creating the live query. This enables crating a live query in a React router loader, then passing it to a view to use with `useLiveQuery`.
See also #375
=> fix(pglite/live): Fix querying views, and extend the return value to allow late attachment of a callback

.changeset/early-windows-walk.md, .changeset/grumpy-turkeys-crash.md, packages/pglite-react/src/hooks.ts, packages/pglite-react/src/provider.tsx, packages/pglite-react/test/hooks.test.tsx, packages/pglite/package.json, packages/pglite/src/live/index.ts, packages/pglite/tests/live.test.ts, pnpm-lock.yaml
Enable passing the return value of a live query directly to `useLiveQuery`. This allows you to create a live query in a react-router loader, then pass it to the route component where it is then attached with `useLiveQuery`.
Related to #374
=> feat(pglite-react) Enable passing the return value of a live query directly to useLiveQuery

.changeset/tasty-seals-attack.md, packages/pglite/package.json
With a recent dependancy bump, builds had started reporting this warning (and similar):
> The condition "types" here will never be used as it comes after both "import" and "require" 
The fix is to place the type exports above the import and require exports.
=> fix: Order of the type exports in package.json

.changeset/clean-squids-obey.md, packages/pglite-sync/src/index.ts, packages/pglite-sync/test/sync.test.ts
Set an electric.syncing config flag in Postgres during a sync transaction to enable user defined triggers to chose how to run during a sync
=> feat: `electric.syncing = true` config flag during a sync

.github/workflows/build_and_test.yml, packages/pglite/src/pglite.ts
Pulls the style check out into separate task so that it doesn't block builds. Very useful for testing ideas without jumping through the style check hoops.
=> chore: Stop stylecheck blocking build

.changeset/violet-peas-check.md, docs/docs/api.md, packages/pglite/src/base.ts, packages/pglite/src/interface.ts, packages/pglite/src/pglite.ts, packages/pglite/tests/basic.test.js
This PR adds support for custom serializers to `QueryOptions`, and adds support for custom parsers and serializers to `PGliteOptions`. The change is non-breaking.
Our use case is using NUMERIC columns to store integers too large for BIGINT. We'd like these values to use the JS native BigInt rather than String, and it's easiest if this happens at the driver layer.
```ts
import { NUMERIC, PGlite, type PGliteOptions } from "@electric-sql/pglite";
export function createPglite(options: PGliteOptions) {
return new PGlite({
serializers: { [NUMERIC]: (x: string | number | bigint) => x.toString() },
parsers: { [NUMERIC]: (x: string) => BigInt(x) },
...options,
});
}
```
Verified locally in an integration test with our framework.
=> feat: add custom parser and serializer to PGlite options

.changeset/dull-items-greet.md, docs/docs/api.md, packages/pglite/examples/basic.html, packages/pglite/src/base.ts, packages/pglite/src/interface.ts, packages/pglite/tests/describe-query.test.ts
This new `describeQuery` method returns the parameter and returns types for a sql query. It can be used to build a type inference system on top of PGlite.
See an example of how to use it here: https://github.com/samwillis/pglite-type-inference
https://github.com/user-attachments/assets/53c45387-7abd-405f-9012-1a590c15c18b
=> feat: Add a describeQuery method

.changeset/fifty-beers-swim.md, packages/pglite-tools/package.json
Next.js, and other bundlers, inspects the `browser` option in package.json to decide what to exclude from a browser bundle. This odds the node fs apis so that it doesnt try and bundle them for the browser.
=> fix(pglite/tools): add node imports to the package.json browser excludes

.changeset/twenty-eagles-pretend.md, packages/pglite/src/parse.ts
This pull request includes changes to the `parseResults` function in the `packages/pglite/src/parse.ts` file. The main goal of these changes is to improve the readability and maintainability of the code by using a `Set` for valid message types and replacing conditional statements with a `switch` statement.
Code readability and maintainability improvements:
* Introduced a `Set` named `VALID_MESSAGE_TYPES` to store valid message types and used it in the `filter` method.
* Replaced multiple `if-else` statements with a `switch` statement to handle different message types more clearly. [[1]](diffhunk://#diff-4392d2058202843607c805897016649278df2f0d9c5e0b9b17b15b2d69e4c9b1R26-R43) [[2]](diffhunk://#diff-4392d2058202843607c805897016649278df2f0d9c5e0b9b17b15b2d69e4c9b1L59-R64) …
=> refactor(parse): Simplify message filtering and processing logic `parseResult`

.changeset/tasty-apples-search.md, .changeset/tough-wombats-fly.md, packages/pglite-react/package.json, packages/pglite-react/src/hooks.ts, packages/pglite-react/src/provider.tsx, packages/pglite-repl/package.json, packages/pglite-repl/src/Repl.tsx, pnpm-lock.yaml
Bump versions of React, React DOM, and related testing libraries to 19.0.0 on pglite-react
=> Support react 19 on pglite-react and pglite-repl

.changeset/lovely-melons-perform.md, packages/pglite/package.json, packages/pglite/tsup.config.ts
This exports the base filesystem implementation so that it can be used to create custom filesystems.
See the OPFS-AHP (https://github.com/electric-sql/pglite/blob/main/packages/pglite/src/fs/opfs-ahp.ts) for an example of how to use this.
**NOTE:** This is a work in progress API, it is not stable, and change significantly in future!
Fixes: #481
=> chore: Export the base filesystem to enable creating custom file systems

packages/pglite/README.md
I believe the packages/pglite/README.md is visible on npmjs.com, so I've updated to contain the same information about building the code and contributing as in the main README.md.
=> Update the packages/pglite/README.md detailing the build and contribute processes

.changeset/sweet-eagles-cross.md, .github/workflows/build_wasm_postgres.yml
Since we're focusing on other things at the moment, we can disable building `postgis`. Re-enable when when we have more time to invest in this.
=> Disable building postgis on CI

.changeset/witty-spiders-type.md, packages/pglite/src/fs/tarUtils.ts, packages/pglite/tests/dump.test.js
Fixes #402
Logic now:
- if it looks like a gzip from mine type or filename, unzip it
- then try and untar
- if there is an error, try and unzip then untar
=> feat: add support for loading compressed dumps via loadDataDir that are not marked as compressed

README.md
Clarifies how to get the files without compiling them locally.
=> Reword how to get the pregenerated WASM build

package.json
Use `cd` instead of `pushd` to change dirs when building wasm.
=> Do not use pushd and popd when pnpm wasm:build

.changeset/cold-bobcats-travel.md, docs/docs/sync.md, packages/pglite-sync/src/index.ts, packages/pglite-sync/test/sync.test.ts
As discussed on Discord, make `shapeKey` mandatory but allow it to be null for non-persisted shapes.
=> Mandatory shapeKey on syncShapeToTable; allow shapeKey to be null

.github/workflows/build_and_test.yml, package.json
We want to run a CI action that mimics the README.md instructions as close as possible.
=> New gh action to pnpm i and pnpm build:all

.changeset/mighty-grapes-refuse.md, docs/docs/api.md, packages/pglite/src/pglite.ts, packages/pglite/tests/clone.test.js
I should add some info to the website about it.
=> Simple clone impl only on PGlite

.changeset/gentle-ways-knock.md, docs/docs/api.md, packages/pglite-sync/package.json, packages/pglite-sync/src/index.ts, packages/pglite-sync/test/sync.test.ts, pnpm-lock.yaml
This fix is something of a stop gap untill we make some larger changes to the plugin and bring in multi table/shape sync.
=> fix: update sync plugin to work with the latest Electric sync server

.changeset/beige-frogs-film.md, packages/pglite-sync/src/index.ts
During initial sync there is nigher the old `offset` or new `lsn` + `op_positon` on each message, we have to fallback to the `stream.lastOffset` value which is the last offset of the final messages in the stream (retrieved from the http header). This replicates the behaviour of the plugin from before the changes to the sync protocol and ensures it will continue to work.
However, we still need to make further changes, and the is likely to include changing the `commitGranularity` option. While this api is useful for incrementally inserting data during initial sync, it is not possible to actually resume from mid way in a snapshot.
The further changes to this api will come as part of a larger refactor to the plugin.
=> Fix of the pglite-sync plugin for latest electric

docs/.vitepress/config.mts
It's better to show what's there. Otherwise one of the main DX points is hidden.
=> docs: expand framework hooks in the side nav.

packages/pglite-sync/src/index.ts, packages/pglite-sync/test-e2e/sync-e2e.test.ts
Fixes OOM when relying on JS spread operator to add more than ~123k values to an array.
=> Sync v2 fixed

packages/pglite-vue/test/hooks.test.ts
See #547 
Thought I add a test as this can serve as an example as well.
=> Add test for useLiveQuery using WHERE ANY

.changeset/strange-news-burn.md, packages/pglite/src/pglite.ts, packages/pglite/tests/live.test.ts
This fixes a race condition in live query unsubscription that could result in live queries failing to update.
The accompanying test fails on the previous version, and passes with this change.
In essence, if you start crating a new live query, but don't await it's subscription - so don't await the query it runs internally at the end - you can interweave a unsubscription of a previous live query. This can result in the unsubscribe removing the listener that has just been added for the new live query.
Technically this is a bug not in the live query (or the react useLiveQuery), but in the `listen` and `unlisted` methods, but it makes sense to test via a live query.
=> fix(pglite/live) handle race condition in live query unsubscription

docs/docs/bundler-support.md
Correct "hou" to "you" for better readability and accuracy in the documentation.
=> docs: fix typo in bundler-support.md

.changeset/tall-otters-thank.md, packages/pglite/src/live/index.ts
This bug can be seen when navigating *away* from the kanban board on [Linearlite example](https://linearlite.examples.electric-sql.com/) - check the console.
=> fix(live): prevent double deallocate of live query prepared statment

docs/docs/framework-hooks/vue.md
Noticed this tiny typo when I was looking into the docs
=> docs: fix typo in vue.md

packages/pglite/src/pglite.ts
I get `TypeError: Cannot read properties of undefined (reading 'dumpTar')` when running the following code:
```typescript
import { PGlite } from "@electric-sql/pglite";
(async () => {
const client = new PGlite("./data");
await client.dumpDataDir()
})();
```
The code assumes the `this.fs` var is initialized while running `dumpDataDir`:
https://github.com/electric-sql/pglite/blob/1777894f4dd4ec9060af3bcbdfd11ae03112f263/packages/pglite/src/pglite.ts#L814
But `this.fs` is not defined when the database is immediately initialized and dumped.
The docs says that:
> Query methods will wait for the waitReady promise to resolve if called before the database has fully initialised, and so it is not necessary to wait for it explicitly.
I think it would be inline with the query methods and close method …
=> Add 'await this._checkReady()' to dumpDataDir

.changeset/slow-pandas-pay.md, packages/pglite-socket/README.md
Makes it clear that `pglite-socket` does NOT support SSL connection at this momen.
=> doc pglite-socket no SSL

.changeset/four-olives-train.md, packages/pglite-sync/src/apply.ts, packages/pglite-sync/test-e2e/sync-e2e.test.ts
In a previous #634 we moved to batching inserts, with a batch split at the param limit of 32k. However there is still a limit to how large a query we can or should push into PGlite at once. This moves to batching inserts with a max of 50mb at once.
FYI @AntonOfTheWoods - May be of interest to you
=> chore(sync): batch inserts by by a max query size of 50mb

packages/pglite-tools/README.md, packages/pglite-tools/tests/pg_dump.test.ts, packages/pglite/examples/pg_dump.html
Small improvements to the tests and docs related to `pg_dump` and `search_path`
=> test and docs: restore search path after dump

.changeset/late-seals-glow.md, packages/pg-protocol/package.json, packages/pglite-react/package.json, packages/pglite-repl/package.json, packages/pglite-socket/package.json, packages/pglite-sync/package.json, packages/pglite-tools/package.json, packages/pglite-vue/package.json, packages/pglite/package.json, pnpm-lock.yaml
Hey :wave:
A teammate had the following issue in a VS Code extension project:
```
Activating extension 'Prisma.prisma-insider' failed: require() of ES Module /home/runner/work/language-tools/language-tools/packages/vscode/node_modules/@electric-sql/pglite-socket/dist/index.js from /home/runner/work/language-tools/language-tools/packages/vscode/node_modules/@prisma/dev/dist/db.cjs not supported.
285
Instead change the require of index.js in /home/runner/work/language-tools/language-tools/packages/vscode/node_modules/@prisma/dev/dist/db.cjs to a dynamic import() which is available in all CommonJS modules..
```
I did some digging and found that `@electric-sql/pglite-socket` had CJS misconfigured in the `package.json`.
This PR fixes `package.json` misconfigurations for dual-package (CJS & …
=> fix(*): dual package misconfigurations.

.changeset/eleven-mirrors-cheer.md, packages/pglite-sync/package.json, pnpm-lock.yaml
the sync plugin incorrectly pined the electric client it used to version 1.0.0, new versions (particularly in the last couple of weeks) include some fixes for 409 caching and ensuring you don't go down the same cached request chain again.
This bumps the version to the latest, and marks it as any version grater than current minor within current major (`^` prefix).
=> bump electric dep
