electric-sql/pglite

README.md

I'm still figuring out the persisted version

Adds Deno in memory

---

README.md

Add missing `()` to `PGLite` instantiation

Update README.md fix example PGLite initialization

---

LICENSE
POSTGRES-LICENSE
README.md
packages/pglite/package.json

chore: Add license

---

packages/pglite/src/fs/idbfs.ts
packages/pglite/src/fs/memoryfs.ts
packages/pglite/src/fs/nodefs.ts
packages/pglite/src/fs/types.ts
packages/pglite/src/pglite.ts

This runs the following sql files from the share dir on first run:
- information_schema.sql
- system_constraints.sql
- system_functions.sql
- system_views.sql
Fixes #8

fix: Add first run step that loads pg_catalog and information_schema sql

---

packages/pglite/README.md
packages/pglite/examples/worker.html
packages/pglite/package.json
packages/pglite/src/index.ts
packages/pglite/src/interface.ts
packages/pglite/src/pglite.ts
packages/pglite/src/worker/index.ts
packages/pglite/src/worker/process.ts
packages/pglite/tsup.config.ts
pnpm-lock.yaml

Same api as normal but import as:
```
import { PGliteWorker } from "@electric-sql/pglite/worker";
const pg = new PGliteWorker();
``

feature: Single tab worker api

---

packages/pglite/src/pglite.ts
packages/pglite/src/types.ts
packages/pglite/tests/basic.test.js
packages/pglite/tests/types.test.js

Improve handling of string and json types, and add parsing+serialising of arrays.

Fix: Improve type parsing

---

packages/repl/.eslintrc.cjs
packages/repl/.gitignore
packages/repl/README.md
packages/repl/index.html
packages/repl/package.json
packages/repl/src-webcomponent/main.tsx
packages/repl/src/App.css
packages/repl/src/App.tsx
packages/repl/src/Repl.css
packages/repl/src/Repl.tsx
packages/repl/src/ReplResponse.tsx
packages/repl/src/ReplTable.tsx
packages/repl/src/index.css
packages/repl/src/main.tsx
packages/repl/src/sqlSupport.ts
packages/repl/src/types.ts
packages/repl/src/utils.ts
packages/repl/src/vite-env.d.ts
packages/repl/tsconfig.json
packages/repl/tsconfig.node.json
packages/repl/vite.config.ts
packages/repl/vite.webcomp.config.ts

A REPL, or terminal, for use in the browser with PGlite, allowing you to have an interactive session with your WASM Postgres in the page.
- Available as both a React.js component and a Web Components
- [CodeMirror](https://codemirror.net) for input editing
- Auto complete, including table and column names from the database
- Input history (up and down keys)
- `\d` PSQL commands (via [psql-describe](https://www.npmjs.com/package/psql-describe))
```
npm install @electric-sql/pglite-repl
```
then to include in a page:
```tsx
import { PGlite } from "@electric-sql/pglite";
import { Repl } from "@electric-sql/pglite-repl";
function MyComponent() {
const pg = new PGlite();
return <>
<Repl pg={pg} />
</>
}
```
The props for the `<Repl>` component are described by this interface:
```ts
// The …
```

 PGlite REPL

---

packages/repl/src-webcomponent/main.tsx
packages/repl/src/Repl.css
packages/repl/src/Repl.tsx
packages/repl/src/ReplResponse.tsx
packages/repl/src/sqlSupport.ts
packages/repl/src/utils.ts
pnpm-lock.yaml

Along with defaulting the exec time to not shown.

REPL loading state

---

packages/repl/package.json
packages/repl/src/Repl.css
packages/repl/src/Repl.tsx
packages/repl/src/uploadButton.ts
packages/repl/src/utils.ts
packages/repl/tsconfig.json
pnpm-lock.yaml

REPL: Add file upload/download for use with `COPY` command

---

.github/workflows/build_and_test.yml
README.md
package.json
packages/pglite/package.json
pnpm-lock.yaml

Also bumped pnpm to v9 to avoid forcing people into an older pnpm version for contributing.
Added the specific versions in the package.json as well which should prevent inconsistent versions of the package manager and node being used.

chore: Add contribution section

---

.changeset/tidy-pumpkins-join.md
packages/pglite-react/package.json

Fix pglite-react exports

---

.gitattributes

Applying override to all files and directories as per [documentation](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#vendored-code) - hopefully fixes the plpgsql

chore: Update git attributes to fix language detection

---

.github/workflows/build_and_test.yml
packages/pglite/eslint.config.js
packages/pglite/package.json
packages/pglite/tests/targets/deno/.gitignore
packages/pglite/tests/targets/deno/basic.test.deno.js
packages/pglite/tests/targets/deno/fs.test.deno.js
packages/pglite/tests/targets/deno/package.json
packages/pglite/tests/targets/deno/pgvector.test.deno.js

chore: Test Deno runtime

---

docs/docs/api.md

Correct listen return type

---

.changeset/fair-points-rhyme.md
packages/pglite-sync/package.json
packages/pglite-sync/src/index.ts
packages/pglite-sync/test/sync.test.ts
pnpm-lock.yaml

Addresses https://github.com/electric-sql/pglite/issues/260
Also adds a basic test for the sync plugin by mocking `ShapeStream`

fix: Update pglite sync to match Electric API

---

.changeset/dry-trains-lay.md
packages/pglite-sync/src/index.ts
packages/pglite-sync/test/sync.test.ts

fix: make pglite-sync options optional

---

packages/pglite/tests/xml.test.ts

Looks like xml all works fine :-D
closes #264

chore: Add basic xml tests

---

docs/docs/repl.md

web-component repl is in its own package

---

.github/workflows/build_wasm_postgres.yml
cibuild/build-all.sh

small adjusts after merging wasi build routing

build extra extensions from script folder ./extra

---

.changeset/slimy-cycles-drum.md
packages/pglite/tests/drop-database.test.ts
patches/postgresql-wasm-16.4/src-backend-storage-ipc-procsignal.c.diff

Important node, this test will hang in a busy loop and CI will continue waiting with no timeout... @pmp-p if you push to this branch, or merge in this test to your own, watch out for your GitHub action minute! You will have to manually kill the run if it hangs.

wip: test case for unclean shutdown after a "drop database"

---

.changeset/few-nails-enjoy.md
packages/pglite/tests/pgvector.test.js
patches/pg_main.c
patches/postgresql-wasm-16.4/src-backend-postmaster-checkpointer.c.diff
patches/postgresql-wasm-16.4/src-backend-storage-ipc-procsignal.c.diff
patches/postgresql-wasm-16.4/src-include-fmgr.h.diff

fix: Extension OIDs in the correct range for dumping with pg_dump

---

.changeset/fuzzy-books-promise.md
packages/pglite/src/types.ts
packages/pglite/tests/types.test.ts

fix: Improve type serialization so it matches exceptions from other libraries

---

docs/docs/orm-support.md

Update the broken drizzle documentation link

Update drizzle documentation link

---

docs/docs/orm-support.md

Added section explaining how to use PGlite with TypeORM.

Add TypeORM support for PGlite

---

.changeset/gentle-olives-hope.md
packages/pglite/src/postgresMod.ts

Replaces #423
Thanks to @firelizzard18!

Make pglite compatible with @jest-environment: node

---

.changeset/swift-news-move.md
packages/pglite/tests/exec-protocol.test.ts
patches/interactive_one.c
patches/postgresql-wasm-16.4/src-backend-libpq-pqcomm.c.diff

wire socket parsing bug found with psycopg3 pipelining prepared statements.

fix socket pipelining read

---

.changeset/late-forks-joke.md
packages/pglite/src/base.ts
packages/pglite/src/interface.ts

fix: correct the return type of the .transaction() method

---

docs/index.md
packages/pglite/tests/targets/deno/basic.test.deno.js
packages/pglite/tests/targets/deno/fs.test.deno.js

(to be readded once we make it work)
Deno tests that I modified should have failed because of a previous PR.

Remove reference to postgis on pglite website 

---

.changeset/long-swans-refuse.md
packages/pglite-tools/src/pg_dump.ts
packages/pglite-tools/tests/pg_dump.test.ts

Gathers the error messages supplied by pg_dump then sets them in the Error thrown.

Add error message when pg_dump fails

---

packages/pglite/tests/basic.test.js

There was a question on #pglite discord channel about this.

Test with using the same parameter multiple times

---

.changeset/itchy-cherries-judge.md
packages/pglite-tools/src/pg_dump.ts
packages/pglite-tools/tests/pg_dump.test.ts

See https://github.com/electric-sql/pglite/issues/561#issuecomment-2711327569

Restore SEARCH_PATH after pg_dump

---

pnpm-workspace.yaml

I've already merged the change in the submodule.

Update submodule that uses a new docker builder image

---

docs/docs/live-queries.md

Solves https://github.com/electric-sql/pglite/issues/536

Update live queries docs

---

.changeset/neat-monkeys-scream.md
packages/pglite/src/live/index.ts
packages/pglite/tests/live.test.ts

https://github.com/electric-sql/pglite/issues/588

Case sensitive table names not working with live

---

packages/pglite-sync/src/index.ts
packages/pglite-sync/test/sync.test.ts

See https://github.com/electric-sql/pglite/issues/624
But I am unsure if forcing `public` schema if not specified is the right way... what if the user sets a different search path?

Quote table name; add public schema if not specified; unit test

---

.changeset/heavy-gorillas-hope.md
packages/pglite-sync/src/apply.ts
packages/pglite-sync/src/index.ts

- remove "initial"-only bulking
- add a plain bulk inserts (in addition to json and copy)

Improve pglite-sync insert management

---

packages/pglite-tools/scripts/bundle-wasm.ts

~DO NOT MERGE!~
As discussed, I moved the new blob to our S3. 
This is now ready for review.

new pg_dump.wasm blob

---

packages/pglite/src/base.ts
packages/pglite/src/errors.ts

Add query data on exception

---

.changeset/plenty-experts-tap.md
packages/pglite/scripts/bundle-wasm.ts

Dist bug fix #729

---

.changeset/pretty-cameras-brake.md
packages/pglite/tests/basic.test.ts
packages/pglite/tests/plpgsql.test.js
pglite-build.sh

requires two more tests https://github.com/electric-sql/pglite/issues/737

switch to pglite-builder sdk (EH fix)

---

.changeset/slimy-countries-rush.md

Update submodule. Details in [PR in postgres-pglite](https://github.com/electric-sql/postgres-pglite/pull/49)

Fixes #657
